package MainTask1;

public class EndsWithException extends Exception {

    public String getMessage() {
        return "В конце номера нет последовательности 1a2b";
    }

}
